'use client'

import { useEffect, useState } from 'react'
import type { TitleView } from '@/lib/achievements/titles'

export default function TitleBadgeManager() {
  const [titles, setTitles] = useState<TitleView[]>([])
  const [selected, setSelected] = useState<string[]>([])
  const [message, setMessage] = useState<string | null>(null)
  const [loading, setLoading] = useState(true)
  useEffect(() => { void (async () => { const response = await fetch('/api/me/titles', { cache: 'no-store' }); const data: unknown = await response.json().catch(() => null); if (!response.ok || !data || typeof data !== 'object') setMessage('칭호를 불러오지 못했습니다.'); else { const result = data as { titles?: TitleView[]; migration_required?: boolean }; if (result.migration_required) setMessage('업적 기능 준비 중입니다.'); setTitles(result.titles ?? []); setSelected((result.titles ?? []).filter((title) => title.equipped_slot !== null).sort((a,b) => (a.equipped_slot ?? 0) - (b.equipped_slot ?? 0)).map((title) => title.id)) } setLoading(false) })() }, [])
  const available = titles.filter((title) => title.available)
  function toggle(id: string) { setSelected((current) => current.includes(id) ? current.filter((value) => value !== id) : current.length < 3 ? [...current, id] : current) }
  function move(index: number, direction: -1 | 1) { const next = [...selected]; const target = index + direction; if (target < 0 || target >= next.length) return; [next[index], next[target]] = [next[target], next[index]]; setSelected(next) }
  async function save() { const response = await fetch('/api/me/titles/equip', { method: 'POST', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify({ titleIds: selected }) }); if (!response.ok) { setMessage('저장하지 못했습니다.'); return } setTitles((current) => current.map((title) => ({ ...title, equipped_slot: selected.indexOf(title.id) + 1 || null }))); setMessage('칭호를 저장했어요.') }
  return <section className="rounded-3xl bg-surface ring-1 ring-line p-6"><div className="text-fg font-extrabold">업적 칭호</div><p className="mt-1 text-xs text-muted">최대 3개를 선택해 순서대로 표시할 수 있어요. TFT 3연승·운영자·Steam 칭호는 조건이 사라지면 자동 해제됩니다.</p>{loading ? <div className="mt-4 text-sm text-muted">불러오는 중...</div> : <><div className="mt-4 grid gap-2">{selected.map((id, index) => { const title = titles.find((item) => item.id === id); return title ? <div key={id} className="flex items-center gap-2 rounded-xl bg-brand/10 px-3 py-2"><span className="text-xs font-black text-brand-ink">{index + 1}</span><span className="flex-1 text-sm font-bold text-fg">{title.label}</span><button type="button" onClick={() => move(index,-1)} className="text-xs text-muted">↑</button><button type="button" onClick={() => move(index,1)} className="text-xs text-muted">↓</button><button type="button" onClick={() => toggle(id)} className="text-xs text-muted">해제</button></div> : null })}</div><div className="mt-4 grid gap-2 sm:grid-cols-2">{available.map((title) => <button type="button" key={title.id} onClick={() => toggle(title.id)} className={`rounded-xl border p-3 text-left ${selected.includes(title.id) ? 'border-brand bg-brand/10' : 'border-line bg-surface-2'}`}><div className="text-sm font-bold text-fg">{title.label}</div><div className="mt-1 text-xs text-muted">{title.description}</div><div className="mt-2 text-[11px] text-brand-ink">{title.kind === 'permanent' ? '보유 업적' : '조건 충족'}</div></button>)}</div><button type="button" onClick={() => void save()} className="mt-4 rounded-xl bg-brand px-4 py-2 text-sm font-bold text-white">칭호 저장</button>{message && <div className="mt-3 text-xs text-muted">{message}</div>}</>}</section>
}
