'use client'

import { useEffect, useState } from 'react'
type Note = { id: string; title: string; summary: string; content: string; is_published: boolean }
const empty = { title: '', summary: '', content: '', isPublished: true }

export default function PatchNotesManager({ season }: { season: { id: number; season_name: string } | undefined }) {
  const [notes, setNotes] = useState<Note[]>([]); const [form, setForm] = useState(empty); const [editing, setEditing] = useState<string | null>(null); const [message, setMessage] = useState('')
  const load = async () => { if (!season) return; const res = await fetch(`/api/admin/tft-patch-notes?seasonId=${season.id}`, { cache: 'no-store' }); const body: unknown = await res.json().catch(() => null); if (body && typeof body === 'object' && Array.isArray((body as { notes?: unknown }).notes)) setNotes((body as { notes: Note[] }).notes) }
  useEffect(() => {
    const timer = window.setTimeout(() => { void load() }, 0)
    return () => window.clearTimeout(timer)
  // season id changes are the only source that requires a reload.
  // eslint-disable-next-line react-hooks/exhaustive-deps
  }, [season?.id])
  const submit = async (event: React.FormEvent) => { event.preventDefault(); if (!season) return; setMessage(''); const method = editing ? 'PATCH' : 'POST'; const payload = { ...form, seasonId: season.id, ...(editing ? { id: editing } : {}) }; const res = await fetch('/api/admin/tft-patch-notes', { method, headers: { 'Content-Type': 'application/json' }, body: JSON.stringify(payload) }); if (!res.ok) { const b: unknown = await res.json().catch(() => null); setMessage(b && typeof b === 'object' && typeof (b as { error?: unknown }).error === 'string' ? (b as { error: string }).error : '저장에 실패했습니다.'); return } setForm(empty); setEditing(null); await load() }
  const edit = (note: Note) => { setEditing(note.id); setForm({ title: note.title, summary: note.summary, content: note.content, isPublished: note.is_published }) }
  const remove = async (id: string) => { if (!window.confirm('패치 노트를 삭제할까요?')) return; await fetch(`/api/admin/tft-patch-notes?id=${id}`, { method: 'DELETE' }); await load() }
  return <section className="rounded-2xl border border-line bg-surface p-6"><h2 className="text-lg font-black text-fg">현재 시즌 패치 노트</h2><p className="mt-1 text-sm text-subtle">{season ? `${season.season_name}에 공개할 게시글을 관리합니다.` : '활성 시즌이 없어 작성할 수 없습니다.'}</p>{season && <><form onSubmit={submit} className="mt-5 space-y-3"><input value={form.title} maxLength={120} onChange={(e) => setForm({ ...form, title: e.target.value })} placeholder="제목" className="w-full rounded-xl border border-line bg-surface-2 px-3 py-2 text-sm" required /><input value={form.summary} maxLength={300} onChange={(e) => setForm({ ...form, summary: e.target.value })} placeholder="요약 (선택)" className="w-full rounded-xl border border-line bg-surface-2 px-3 py-2 text-sm" /><textarea value={form.content} maxLength={20000} onChange={(e) => setForm({ ...form, content: e.target.value })} placeholder="본문" className="min-h-28 w-full rounded-xl border border-line bg-surface-2 px-3 py-2 text-sm" required /><label className="flex items-center gap-2 text-sm text-muted"><input type="checkbox" checked={form.isPublished} onChange={(e) => setForm({ ...form, isPublished: e.target.checked })} />바로 공개</label><button className="rounded-lg bg-brand px-4 py-2 text-sm font-bold text-white">{editing ? '수정 저장' : '게시글 등록'}</button>{editing && <button type="button" onClick={() => { setEditing(null); setForm(empty) }} className="ml-2 text-sm text-muted">취소</button>}{message && <p className="text-sm text-danger-ink">{message}</p>}</form><ul className="mt-6 divide-y divide-line">{notes.map((note) => <li key={note.id} className="flex items-center justify-between gap-3 py-3"><div><p className="font-bold text-fg">{note.title}</p><p className="text-xs text-subtle">{note.is_published ? '공개' : '초안'}</p></div><div className="flex gap-2"><button type="button" onClick={() => edit(note)} className="text-sm text-brand-ink">수정</button><button type="button" onClick={() => void remove(note.id)} className="text-sm text-danger-ink">삭제</button></div></li>)}</ul></>}</section>
}
